### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by jcubic** [ritterim/skellyCSS#19]
## 🔧 Enhancement Request 

This type of placeholder animations often have animations

## Who is asking for the feature?

I'm adding this feature request for myself, no one is forcing me to do this.

## What business problem is this hoping to solve?

It will improve the look of the skeleton.

Here is example how the animation may look like https://skeletonreact.com/

**Comment by mackenziegates** [comment]
@mrtrimble thoughts?

**Comment by mrtrimble** [comment]
hey there @jcubic, thanks for reaching out!

This project actually does have animations built in, check out the documentation here:
https://github.com/ritterim/skellyCSS?tab=readme-ov-file#animation

Codepen example: 
https://codepen.io/mrtrimble/pen/QWeXGdQ/c1b63edcb063f121736312aaaf15a2f1

Also, I've started working on a web component version of skelly, which you can find over here (no animations yet!):
https://github.com/mrtrimble/skelly-wc

**Comment by jcubic** [comment]
Can you have animation without including JavaScript file?

**Comment by mrtrimble** [comment]
> Can you have animation without including JavaScript file?

@jcubic - Absolutely! Just need to add a bit more to the HTML:

```html
<div>
  <p class="skeleton">
    <span class="skeleton__line">
      <span class="skeleton--animation"></span>
    </span>
    <span class="skeleton__line">
      <span class="skeleton--animation"></span>
    </span>
    <span class="skeleton__line">
      <span class="skeleton--animation"></span>
    </span>
    <span class="skeleton__line">
      <span class="skeleton--animation"></span>
    </span>
  </p>
</div>
```

The JS basically just generates that for you.

**Comment by jcubic** [comment]
Awesome, thanks.
